export const generatedSourceHeader = [
  "/* eslint-disable */",
  "/* oxlint-disable */",
  "// biome-ignore-all lint: generated by @openmirai/intl-compiler",
  "// biome-ignore-all format: generated by @openmirai/intl-compiler",
  "// biome-ignore-all assist/source/organizeImports: generated by @openmirai/intl-compiler",
  "// @generated by @openmirai/intl-compiler. Do not edit.",
].join("\n");

export function withGeneratedSourceHeader(source: string): string {
  return `${generatedSourceHeader}\n${source}`;
}
